// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"fullscreen","status":false,"description":"","parameters":{}},
{"name":"N_StartFullscreen","status":true,"description":"Start game in fullscreen","parameters":{"textExit":"Exit","textToDesktop":"To Desktop"}}
];
